USE [CORPORERM]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER FUNCTION [dbo].[FOP_GET_HSTSECAO]
(
     @CODCOLIGADA int
    ,@CHAPA VARCHAR(16)
	,@DATA DATETIME
)
RETURNS TABLE AS RETURN
(
    SELECT 
		 H.CODCOLIGADA
		,H.CODSECAO AS 'CODSECAO_HIST'
		,P.DESCRICAO AS 'DESC_SECAO_HIST'
      FROM DBO.PFHSTSEC (NOLOCK) H
	  JOIN DBO.PSECAO   (NOLOCK) P ON (H.CODCOLIGADA = P.CODCOLIGADA AND H.CODSECAO = P.CODIGO)
     WHERE H.CODCOLIGADA = @CODCOLIGADA
	   AND H.CHAPA=@CHAPA
       AND H.DTMUDANCA = (SELECT MAX(HH.DTMUDANCA)
                            FROM DBO.PFHSTSEC (NOLOCK) HH 
                           WHERE HH.CODCOLIGADA = H.CODCOLIGADA 
						     AND HH.CHAPA = H.CHAPA
                             AND HH.DTMUDANCA <= @DATA)
)