USE [CORPORERM]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER FUNCTION [dbo].[FOP_GET_HISTSAL]
(
    
     @CODCOLIGADA int
    ,@CHAPA VARCHAR(16)
	,@DATA DATETIME
)
RETURNS TABLE AS RETURN
(
    SELECT 
		 H.CODCOLIGADA
		,H.SALARIO AS 'SALARIO_HIST'
		,H.JORNADA AS 'JORNADA_HIST'
      FROM DBO.PFHSTSAL (NOLOCK) H
     WHERE H.CODCOLIGADA = @CODCOLIGADA
	   AND H.CHAPA=@CHAPA
       AND H.DTMUDANCA = (SELECT MAX(HH.DTMUDANCA)
                            FROM DBO.PFHSTSAL (NOLOCK) HH 
                           WHERE HH.CODCOLIGADA = H.CODCOLIGADA 
						     AND HH.CHAPA = H.CHAPA
                             AND HH.DTMUDANCA <= @DATA)
)
