USE CORPORERM	
GO

CREATE OR ALTER PROCEDURE [DBO].[SP_FOP_GET_CONTRACHEQUE_CHAPA] 
(
	 @CODCOLIGADA INT 
	,@ANOCOMP INT 
	,@ANOCOMPFIM INT = @ANOCOMP
	,@MESCOMP INT 
	,@MESCOMPFIM INT = @MESCOMP
	,@CHAPA VARCHAR(16)  
	,@NROPERIODO INT 
	,@NROPERIODOFIM INT = @NROPERIODO 
	,@CRTLINHAS INT = 15 
	,@DUPLICADO BIT = 0
)
AS 
BEGIN

	SET NOCOUNT ON;

	DECLARE @DATAINICIAL DATETIME = DATEFROMPARTS(@ANOCOMP, @MESCOMP, 1);
	DECLARE @DATAFINAL	 DATETIME = DATEFROMPARTS(@ANOCOMPFIM, @MESCOMPFIM, 1);
	
	
	;WITH TAB_FILTRO
	AS
	(
		SELECT 
			 PF.CODCOLIGADA 
			,PF.CHAPA 
			,PF.ANOCOMP
			,PF.MESCOMP
			,PF.NROPERIODO
		FROM DBO.VW_PFPERFF PF
		WHERE PF.CODCOLIGADA = @CODCOLIGADA
		AND DATEFROMPARTS(PF.ANOCOMP, PF.MESCOMP, 1) 
			BETWEEN @DATAINICIAL AND @DATAFINAL
		AND PF.NROPERIODO BETWEEN  @NROPERIODO AND @NROPERIODOFIM
		AND PF.CHAPA = @CHAPA
	)
	, TAB_DADOS_FICHA
	AS
	(
		SELECT 
			 ROW_NUMBER() OVER(PARTITION BY PF.CODCOLIGADA,PF.CHAPA,PF.ANOCOMP,PF.MESCOMP,PF.NROPERIODO,E.PROVDESCBASE 
						  ORDER BY PF.CODCOLIGADA,PF.CHAPA,PF.ANOCOMP,PF.MESCOMP,PF.NROPERIODO,E.PROVDESCBASE ) AS 'SEQ'
			,PF.CODCOLIGADA 
			,PF.CHAPA
			,PF.ANOCOMP 
			,PF.MESCOMP 
			,PF.NROPERIODO
			,PF.CODEVENTO 
			,E.DESCRICAO
			,E.PROVDESCBASE
			,IIF(PF.HORA > 0 , [dbo].[UTL_GET_HORA] (PF.HORA), CAST(PF.REF AS VARCHAR(25))) AS 'REF'	
			,PF.VALOR
		FROM DBO.VW_PFFINANC PF
		JOIN TAB_FILTRO F ON (PF.CODCOLIGADA = F.CODCOLIGADA AND PF.CHAPA = F.CHAPA 
		                  AND PF.ANOCOMP = F.ANOCOMP AND PF.MESCOMP = F.MESCOMP
						  AND PF.NROPERIODO = F.NROPERIODO)
		JOIN DBO.PEVENTO E ON (PF.CODCOLIGADA = E.CODCOLIGADA AND PF.CODEVENTO = E.CODIGO)
		WHERE E.PROVDESCBASE <> 'B'
		AND PF.VALOR <> 0 
	)
	, TAB_DADOS_PROV
	AS
	(
		SELECT 
			 SEQ
			,CODCOLIGADA
			,CHAPA
			,ANOCOMP
			,MESCOMP
			,NROPERIODO
			,CODEVENTO
			,DESCRICAO
			,PROVDESCBASE
			,REF
			,VALOR
		FROM TAB_DADOS_FICHA
		WHERE PROVDESCBASE = 'P'
	)
	, TAB_DADOS_DESC
	AS
	(
		SELECT 
			 SEQ
			,CODCOLIGADA
			,CHAPA
			,ANOCOMP
			,MESCOMP
			,NROPERIODO
			,CODEVENTO
			,DESCRICAO
			,PROVDESCBASE
			,REF
			,VALOR
		FROM TAB_DADOS_FICHA
		WHERE PROVDESCBASE = 'D'
	)
	, TAB_DADOS_LIMITE
	AS
	(
		SELECT 
			 IIF(MAXSEQ > @CRTLINHAS, MAXSEQ , @CRTLINHAS) AS 'LINHAS'
			,CODCOLIGADA
			,CHAPA 
			,ANOCOMP
			,MESCOMP
			,NROPERIODO
		FROM (
			SELECT 
				  MAX(SEQ)  AS 'MAXSEQ'
				 ,CODCOLIGADA
				 ,CHAPA
				 ,ANOCOMP
				 ,MESCOMP
				 ,NROPERIODO
			FROM TAB_DADOS_FICHA
			GROUP BY CODCOLIGADA
				 ,CHAPA
				 ,ANOCOMP
				 ,MESCOMP
				 ,NROPERIODO) TAB
	)
	, TAB_DADOS_BASE
	AS
	(
		SELECT 
			 1 AS 'SEQ'
			,LINHAS
			,CODCOLIGADA
			,CHAPA
			,ANOCOMP
			,MESCOMP
			,NROPERIODO
		FROM TAB_DADOS_LIMITE 
	
		UNION ALL
	
		SELECT 
			 SEQ + 1 
			,LINHAS
			,CODCOLIGADA
			,CHAPA
			,ANOCOMP
			,MESCOMP
			,NROPERIODO
		FROM TAB_DADOS_BASE
		WHERE SEQ < LINHAS
	)
	, TAB_DADOS
	AS
	(
		SELECT 
			 TB.SEQ
			,TB.CODCOLIGADA
			,TB.CHAPA
			,TB.ANOCOMP
			,TB.MESCOMP
			,TB.NROPERIODO
			,DATEADD(MS,-3,DATEADD(MM,1,CONVERT(DATETIME, DATEFROMPARTS(TB.ANOCOMP,TB.MESCOMP, 1), 120))) AS 'DATAREF'
			,P.PCODEVENTO
			,P.PDESCRICAO
			,P.PREF
			,P.PVALOR
			,D.DCODEVENTO
			,D.DDESCRICAO
			,D.DREF
			,D.DVALOR
		FROM TAB_DADOS_BASE TB
		OUTER APPLY 
		(
			SELECT 
				 P1.CODEVENTO AS 'PCODEVENTO'
				,P1.DESCRICAO AS 'PDESCRICAO'
				,P1.REF AS 'PREF'
				,P1.VALOR AS 'PVALOR'
			FROM TAB_DADOS_PROV P1
			WHERE P1.CODCOLIGADA = TB.CODCOLIGADA 
			AND P1.CHAPA = TB.CHAPA 
			AND P1.ANOCOMP = TB.ANOCOMP 
			AND P1.MESCOMP = TB.MESCOMP 
			AND P1.NROPERIODO = TB.NROPERIODO
			AND P1.SEQ = TB.SEQ
		) P  
		OUTER APPLY 
		(
			SELECT 
				 D1.CODEVENTO AS 'DCODEVENTO'  
				,D1.DESCRICAO AS 'DDESCRICAO'
				,D1.REF AS 'DREF'
				,D1.VALOR AS 'DVALOR'
			FROM TAB_DADOS_DESC D1
			WHERE D1.CODCOLIGADA = TB.CODCOLIGADA 
			AND D1.CHAPA = TB.CHAPA 
			AND D1.ANOCOMP = TB.ANOCOMP 
			AND D1.MESCOMP = TB.MESCOMP 
			AND D1.NROPERIODO = TB.NROPERIODO
			AND D1.SEQ = TB.SEQ
		) D
	)
	SELECT 
		 TD.SEQ
		,1 AS 'NRO'
	    ,TD.CODCOLIGADA
	    ,TD.CHAPA
	    ,TD.ANOCOMP
	    ,TD.MESCOMP
	    ,TD.NROPERIODO
	    ,TD.DATAREF
	    ,TD.PCODEVENTO
	    ,TD.PDESCRICAO
	    ,TD.PREF
	    ,TD.PVALOR
	    ,TD.DCODEVENTO
	    ,TD.DDESCRICAO
	    ,TD.DREF
	    ,TD.DVALOR
	FROM TAB_DADOS TD
	
	UNION ALL 
	
	SELECT 
		 TD.SEQ
		,2 AS 'NRO'
	    ,TD.CODCOLIGADA
	    ,TD.CHAPA
	    ,TD.ANOCOMP
	    ,TD.MESCOMP
	    ,TD.NROPERIODO
	    ,TD.DATAREF
	    ,TD.PCODEVENTO
	    ,TD.PDESCRICAO
	    ,TD.PREF
	    ,TD.PVALOR
	    ,TD.DCODEVENTO
	    ,TD.DDESCRICAO
	    ,TD.DREF
	    ,TD.DVALOR
	FROM TAB_DADOS TD
	WHERE @DUPLICADO = 1 
	ORDER BY TD.CODCOLIGADA, TD.CHAPA, TD.ANOCOMP , TD.MESCOMP , TD.NROPERIODO, 2, TD.SEQ	
END 