CREATE PROC SP_FOP_GET_CONTABILIZACAO
(
	 @CODCOLIGADA INT 
	,@DATAINICIAL DATETIME
	,@DATAFINAL   DATETIME
)
AS

BEGIN

DECLARE @DATAFINALAJS DATETIME = DATEADD(DAY,1,@DATAFINAL)

;WITH TAB_DADOS
AS
(
	SELECT 
		 C.CODCOLIGADA
		,C.IDPARTIDA
		,C.[DATA]
      	,C.CODCCUSTO
		,C.CREDITO
		,(SELECT DESCRICAO FROM DBO.CCONTA (NOLOCK) WHERE CODCOLIGADA = C.CODCOLIGADA AND CODCONTA=C.CREDITO) AS 'DESC_CREDITO'
		,C.DEBITO
		,(SELECT DESCRICAO FROM DBO.CCONTA (NOLOCK) WHERE CODCOLIGADA = C.CODCOLIGADA AND CODCONTA=C.DEBITO)  AS 'DESC_DEBITO'
		,P.CODLOTE
		,P.CHAPA
		,F.NOME
		,F.CODSINDICATO
		,(SELECT H.CODSECAO 
      	   FROM DBO.PFHSTSEC H (NOLOCK)
      	  WHERE H.CHAPA = F.CHAPA
		    AND H.CODCOLIGADA = F.CODCOLIGADA
      	    AND H.DTMUDANCA=(SELECT MAX(DTMUDANCA) 
      	  				       FROM DBO.PFHSTSEC HH (NOLOCK) 
      	  				      WHERE HH.CHAPA = H.CHAPA
		  				        AND HH.CODCOLIGADA = H.CODCOLIGADA
      							AND HH.DTMUDANCA < @DATAFINALAJS)) AS 'SECAO'
		,'ENCARGO' AS 'TIPO'
		,P.CODENCARGO AS 'CODIGO', 
      	 E.DESCRICAO,
      	 P.VALOR
	FROM DBO.CPARTIDA C (NOLOCK)
	JOIN DBO.PITEMPARTIDA P (NOLOCK) ON (C.CODCOLIGADA =C.CODCOLIGADA AND C.IDPARTIDA=P.IDPARTIDA)
	JOIN DBO.PENCARGO E (NOLOCK) ON (E.CODCOLIGADA=C.CODCOLIGADA AND P.CODENCARGO=E.CODIGO)
	JOIN DBO.PFUNC F (NOLOCK) ON (C.CODCOLIGADA=F.CODCOLIGADA AND F.CHAPA=P.CHAPA)      
	WHERE C.CODCOLIGADA = @CODCOLIGADA
	AND C.[DATA] >= @DATAINICIAL 
	AND C.[DATA] < @DATAFINALAJS
	AND C.INTEGRAAPLICACAO = 'P'
	AND P.CODENCARGO IS NOT NULL
      
    UNION 
      
	SELECT 
		 C.CODCOLIGADA
		,C.IDPARTIDA
		,C.[DATA]
		,C.CODCCUSTO
		,C.CREDITO
		,(SELECT DESCRICAO FROM DBO.CCONTA (NOLOCK) WHERE CODCOLIGADA = C.CODCOLIGADA AND CODCONTA=C.CREDITO) AS 'DESC_CREDITO'
		,C.DEBITO
		,(SELECT DESCRICAO FROM DBO.CCONTA (NOLOCK) WHERE CODCOLIGADA = C.CODCOLIGADA AND CODCONTA=C.DEBITO)  AS 'DESC_DEBITO'
		,P.CODLOTE
		,P.CHAPA
		,F.NOME
		,F.CODSINDICATO
		,(SELECT H.CODSECAO 
      	   FROM DBO.PFHSTSEC H (NOLOCK)
      	  WHERE H.CHAPA = F.CHAPA
		    AND H.CODCOLIGADA = F.CODCOLIGADA
      	    AND H.DTMUDANCA=(SELECT MAX(DTMUDANCA) 
      	 					  FROM DBO.PFHSTSEC HH (NOLOCK)
      	 					 WHERE HH.CHAPA = H.CHAPA
		 					   AND HH.CODCOLIGADA = H.CODCOLIGADA
      	 					   AND HH.DTMUDANCA < @DATAFINALAJS) ) AS 'SECAO', 
      	 'EVENTO' AS TIPO
		,P.CODEVENTO AS 'CODIGO'
		,E.DESCRICAO
		,P.VALOR
	FROM DBO.CPARTIDA C (NOLOCK)
	JOIN DBO.PITEMPARTIDA P (NOLOCK) ON (C.CODCOLIGADA =C.CODCOLIGADA AND C.IDPARTIDA=P.IDPARTIDA)
	JOIN DBO.PEVENTO E (NOLOCK) ON (E.CODCOLIGADA=C.CODCOLIGADA AND P.CODEVENTO=E.CODIGO)
	JOIN DBO.PFUNC F (NOLOCK) ON (C.CODCOLIGADA=F.CODCOLIGADA AND F.CHAPA=P.CHAPA)
	WHERE C.CODCOLIGADA = @CODCOLIGADA
	AND C.[DATA] >= @DATAINICIAL 
	AND C.[DATA] < @DATAFINALAJS
	AND C.INTEGRAAPLICACAO = 'P'
	AND P.CODEVENTO IS NOT NULL 
) 
SELECT 
	  T.CODCOLIGADA 
	 ,T.IDPARTIDA
	 ,T.[DATA]
	 ,T.CODCCUSTO
	 ,T.CREDITO
	 ,T.DESC_CREDITO
	 ,T.DEBITO
	 ,T.DESC_DEBITO
	 ,T.CODLOTE
	 ,T.CHAPA
	 ,T.NOME
	 ,T.CODSINDICATO
	 ,T.SECAO
	 ,T.TIPO
	 ,T.CODIGO
	 ,T.DESCRICAO
	 ,T.VALOR
FROM TAB_DADOS T

END
