USE CORPORERM
GO

CREATE OR ALTER VIEW [DBO].[VW_PFFINANC]
--WITH SCHEMABINDING
AS
SELECT 
     [CODCOLIGADA]
    ,[CHAPA]
    ,[ANOCOMP]
    ,[MESCOMP]
    ,[NROPERIODO]
    ,[CODEVENTO]
    ,[DTPAGTO]
    ,[HORA]
    ,[REF]
    ,[VALOR]
    ,[VALORORIGINAL]
    ,[ALTERADOMANUAL]
    ,[VERBAFERIAS]
    ,[ORIGEMMOV]
    ,[RECCREATEDBY]
    ,[RECCREATEDON]
    ,[RECMODIFIEDBY]
    ,[RECMODIFIEDON]
    ,[VERBARESILICAO]
    ,[VERBADIFERENCA]
FROM [DBO].[PFFINANC]

UNION 

SELECT 
     [CODCOLIGADA]
    ,[CHAPA]
    ,[ANOCOMP]
    ,[MESCOMP]
    ,[NROPERIODO]
    ,[CODEVENTO]
    ,[DTPAGTO]
    ,[HORA]
    ,[REF]
    ,[VALOR]
    ,[VALORORIGINAL]
    ,[ALTERADOMANUAL]
    ,[VERBAFERIAS]
    ,[ORIGEMMOV]
    ,[RECCREATEDBY]
    ,[RECCREATEDON]
    ,[RECMODIFIEDBY]
    ,[RECMODIFIEDON]
    ,[VERBARESILICAO]
    ,[VERBADIFERENCA]
FROM [DBO].[PFFINANCCOMPL] 
