USE CORPORERM
GO 

EXEC SP_UTL_SET_ZCONSTANTES
	 @TABELA = 'PFUNC'
	,@CAMPO = 'CODCATEGORIAESOCIAL' 
	,@TABELA_DINAM = 'PESOCIALCATTRAB' 
	,@CAMPO_DINAM = 'CODCLIENTE' 
	,@GDINAM_CODIGO = 'PESOCIALCT'
	,@GDINAM_APLICACAO = 'P'
