USE [CORPORERM]
GO 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;

SELECT TOP 100
	 F.CODCOLIGADA 
	,F.IDLAN
	,F.DATACRIACAO
	,F.PAGREC
	,C1.[STATUS] AS 'DESC_PAGREC'
	,F.NFOUDUP
	,C2.[STATUS] AS 'DESC_NFOUDUP'
	,F.STATUSLAN
	,C3.[STATUS] AS 'DESC_STATUSLAN'
	,F.TIPOCONTABILLAN
	,C4.[STATUS] AS 'DESC_TIPOCONTABILLAN'
	,F.CLASSIFICACAO
	,C5.[STATUS] AS 'DESC_TCLASSIFICACAO'
FROM DBO.FLAN F 
CROSS APPLY DBO.UTL_GET_CONSTANTE('FLAN','PAGREC',F.PAGREC) C1
CROSS APPLY DBO.UTL_GET_CONSTANTE('FLAN','NFOUDUP',F.NFOUDUP) C2
CROSS APPLY DBO.UTL_GET_CONSTANTE('FLAN','STATUSLAN',F.STATUSLAN) C3
CROSS APPLY DBO.UTL_GET_CONSTANTE('FLAN','STATUSLAN',F.STATUSLAN) C4

OUTER APPLY DBO.UTL_GET_CONSTANTE('FLAN','CLASSIFICACAO',F.CLASSIFICACAO) C5
WHERE F.CODCOLIGADA = 1 
AND F.DATACRIACAO >= '2022-10-01' 
