CREATE     PROC SP_UTL_SET_ZCONSTANTES
(
	 @TABELA VARCHAR(250)
	,@CAMPO VARCHAR(250)
	,@TABELA_DINAM VARCHAR(250)
	,@CAMPO_DINAM VARCHAR(100)
	,@GDINAM_CODIGO VARCHAR(100)
	,@GDINAM_APLICACAO VARCHAR(10)
)
AS 
BEGIN 


DECLARE @TAB TABLE 
( 
	 TABELA VARCHAR(250)
	,CAMPO VARCHAR(250)
	,TABELA_DINAM VARCHAR(250)
	,CAMPO_DINAM VARCHAR(100)
	,GDINAM_CODIGO VARCHAR(100)
	,GDINAM_APLICACAO VARCHAR(10)
);
DECLARE @CR_TABELA VARCHAR(250)
DECLARE @CR_CAMPO  VARCHAR(250)
DECLARE @CR_TABELA_DINAM VARCHAR(250)
DECLARE @CR_CAMPO_DINAM  VARCHAR(100)
DECLARE @CR_GDINAM_CODIGO  VARCHAR(100)
DECLARE @CR_GDINAM_APLICACAO  VARCHAR(10)


/*PREENCHE TABELA */
INSERT INTO @TAB 
(
	 TABELA
	,CAMPO
	,TABELA_DINAM
	,CAMPO_DINAM
	,GDINAM_CODIGO
	,GDINAM_APLICACAO
)
SELECT @TABELA, @CAMPO, @TABELA_DINAM, @CAMPO_DINAM, @GDINAM_CODIGO, @GDINAM_APLICACAO

/*EXCLUI DADOS*/
DELETE Z 
FROM @TAB T
JOIN DBO.ZCONSTANTES Z 
	ON ( T.TABELA = Z.TABELA 
	 AND T.CAMPO = Z.CAMPO 
	 AND T.TABELA_DINAM = Z.TABELA_DINAM 
	 AND T.CAMPO_DINAM = Z.CAMPO_DINAM)

  
/*INSERT DADOS*/
DECLARE CR CURSOR FOR  SELECT TABELA, CAMPO, TABELA_DINAM, CAMPO_DINAM, GDINAM_CODIGO , GDINAM_APLICACAO  FROM @TAB

OPEN CR  
FETCH NEXT FROM CR INTO @CR_TABELA , @CR_CAMPO, @CR_TABELA_DINAM, @CR_CAMPO_DINAM, @CR_GDINAM_CODIGO, @CR_GDINAM_APLICACAO

WHILE @@FETCH_STATUS = 0  
BEGIN  
    DECLARE @SQL VARCHAR(MAX) = 
	
	CONCAT ('
	INSERT INTO DBO.ZCONSTANTES
	(
		 TABELA
		,CAMPO
		,CODSTATUS
		,STATUS
		,OBSERVACAO
		,CODCOLIGADA
		,GDINAM_CODIGO
		,GDINAM_APLICACAO
		,TABELA_DINAM
		,CAMPO_DINAM
		,PODEALTERAR_DINAM
	)
	SELECT 
		 ''',@CR_TABELA,''' AS ''TABELA''
		,''',@CR_CAMPO,''' AS ''CAMPO'' 
		,',@CR_CAMPO_DINAM,' AS ''CODSTATUS'' 
		,DESCRICAO AS ''STATUS'' 
		,NULL AS ''OBSERVACAO'' 
		,0 AS ''CODCOLIGADA'' 
		,''',@CR_GDINAM_CODIGO ,''' AS ''GDINAM_CODIGO''
		,''',@CR_GDINAM_APLICACAO, ''' AS ''GDINAM_APLICACAO''
		,''',@CR_TABELA_DINAM,''' AS ''TABELA_DINAM''
		,''',@CR_CAMPO_DINAM,''' AS ''CAMPO_DINAM''
		,ISNULL(PODEALTERAR, 0) AS ''PODEALTERAR_DINAM''
	FROM DBO.', @CR_TABELA_DINAM, ' WITH (NOLOCK)
	OPTION (MAXDOP 1)'
	)

	EXEC (@SQL)
	PRINT @SQL

	FETCH NEXT FROM CR INTO @CR_TABELA , @CR_CAMPO, @CR_TABELA_DINAM, @CR_CAMPO_DINAM, @CR_GDINAM_CODIGO, @CR_GDINAM_APLICACAO
END 

CLOSE CR  
DEALLOCATE CR 


END 
