CREATE FUNCTION [dbo].[UTL_GET_CONSTANTE]
(
    @TABELA NVARCHAR(250),
    @CAMPO NVARCHAR(250),
	@CODIGO NVARCHAR(50)
)
RETURNS TABLE AS RETURN
(
    SELECT 
		 CODSTATUS 
		,[STATUS]
		,OBSERVACAO
	FROM DBO.ZCONSTANTES
	WHERE TABELA = @TABELA 
	AND CAMPO = @CAMPO 
	AND CODSTATUS = @CODIGO
)
