USE [CORPORERM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZCONSTANTES]
(
	[TABELA] [nvarchar](500) NOT NULL,
	[CAMPO] [nvarchar](500) NOT NULL,
	[CODSTATUS] [nvarchar](50) NOT NULL,
	[STATUS] [nvarchar](500) NULL,
	[OBSERVACAO] [nvarchar](1000) NULL,
	[CODCOLIGADA] [smallint] NOT NULL,
	[GDINAM_CODIGO] [nvarchar](100) NULL,
	[GDINAM_APLICACAO] [nvarchar](10) NULL,
	[TABELA_DINAM] [nvarchar](100) NULL,
	[CAMPO_DINAM] [nvarchar](100) NULL,
	[PODEALTERAR_DINAM] [bit] NULL,
	CONSTRAINT [PKZCONSTANTES] PRIMARY KEY CLUSTERED 
	(
		[TABELA] ASC,
		[CAMPO] ASC,
		[CODSTATUS] ASC,
		[CODCOLIGADA] ASC
	)
	WITH 
	(
		 PAD_INDEX = OFF
		,STATISTICS_NORECOMPUTE = OFF
		,IGNORE_DUP_KEY = OFF
		,ALLOW_ROW_LOCKS = ON
		,ALLOW_PAGE_LOCKS = ON
		,FILLFACTOR = 99
		,OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
		,DATA_COMPRESSION = PAGE
	) ON [PRIMARY]
) ON [PRIMARY]
GO

